### ISSUE TITLE
Error in "sh test.sh"

### ISSUE THREAD

**Issue by mmehdirk** [bcmi/ObjectStitch-Image-Composition#2]
Hi, 
Thanks for providing your work. I am trying to get inference using your code and I did each step based on your instructions. But I got this error when I "sh test.sh"

yaml.composer.ComposerError: found undefined alias 'dataset_dir'
  in "/work/user/ObjectStitch-Image-Composition/configs/v1.yaml", line 87, column 28

**Comment by Shrav211** [comment]
You will have to define an anchor for the value path-to-openimages. This allows you to reference the same value multiple times in the YAML document using an alias (*dataset_dir) without repeating it.

go to configs/v1.yaml

and make the following changes at line 78 -

`  dataset_dir: &dataset_dir path-to-openimages` 

Cheers!

P.S - I created a PR after making the changes.
